name: Github CI

on:
  push:
    branches: ["beta"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pipeline
        uses: actions/checkout@v3

      - name: Initializing Yarn
        uses: Borales/actions-yarn@v3

      - name: Removing Node Modules
        run: sudo rm -rf /home/runner/work/notehut/notehut/node_modules/

      - name: Installing Dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pipeline
        uses: actions/checkout@v3

      - name: Initializing Yarn
        uses: Borales/actions-yarn@v3

      - name: Removing Node Modules
        run: sudo rm -rf /home/runner/work/notehut/notehut/node_modules/

      - name: Installing Dependencies
        run: yarn

      - name: Checking Typescript
        run: yarn ts-check

  build:
    runs-on: ubuntu-latest
    needs: [lint, typescript-check]
    steps:
      - name: Checkout Pipeline
        uses: actions/checkout@v3

      - name: Initializing Yarn
        uses: Borales/actions-yarn@v3

      - name: Removing Node Modules
        run: sudo rm -rf /home/runner/work/notehut/notehut/node_modules/

      - name: Installing Dependencies
        run: yarn

      - name: Building
        run: yarn build

  # cypress-tests:
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # Install dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Running Cypress Tests
  #       uses: cypress-io/github-action@v4
  #       with:
  #         start: yarn dev
  #         wait-on: "http://localhost:3000"
  #         wait-on-timeout: 120
  #         config: baseUrl=http://localhost:3000
  #         record: true
  #         browser: electron
  #       env:
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
  #         VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
