# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: ["beta"]
  pull_request:
    branches: ["master"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v3
      - run: yarn install
      - run: yarn ts-check
      - run: yarn build
