name: Node CI

on:
  push:
    branches: ["beta"]
  pull_request:
    branches: ["master"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pipeline
        uses: actions/checkout@v3

      - name: Initializing Yarn
        uses: Borales/actions-yarn@v3

      - name: Installing Dependencies
        run: yarn install

      - name: Checking Typescript
        run: yarn ts-check

      - name: Building
        run: yarn build
